<?php

/**
 * PluginmdAssetYoutube
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdAssetYoutube extends BasemdAssetYoutube
{
  public function getSize(){
    return 20;
  }
  
  public function getFilename(){
    return 'chugas_' . rand(0, 1000);
  }
  
  public function getUrl(){
    return '';
  }
  
  public function getIcon(){
    return '';
  }
}