<?php

/**
 * PluginmdAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdAssetTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdAssetTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdAsset');
  }

}