<?php

/**
 * PluginmdAssetYoutubeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdAssetYoutubeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdAssetYoutubeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdAssetYoutube');
    }

    public function getVideoByAlbum($album_id)
    {
    	$yt = $this->createQuery('yt')
    			   ->where('yt.md_album_id =?', $album_id)
    			   ->fetchOne();
    	return $yt;
    }
}