<?php

/**
 * PluginmdAssetVimeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdAssetVimeoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdAssetVimeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdAssetVimeo');
    }
}