<?php

/**
 * PluginmdAssetIssuuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdAssetIssuuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdAssetIssuuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdAssetIssuu');
    }
}