<?php

/**
 * PluginmdAssetAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdAssetAlbumTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdAssetAlbumTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdAssetAlbum');
  }

  public function retrieveByObject($object_class, $object_id, $query = false){
    $q = $this->createQuery('a')
      ->where('a.object_class = ?', $object_class)
      ->andWhere('a.object_id = ?', $object_id)
      ->orderBy('a.created_at DESC');

    if($query) return $q;
    else return $q->execute();
  }

}