<?php

/**
 * PluginmdAssetFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdAssetFileTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdAssetFileTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdAssetFile');
  }

  public function retrieveFiles($md_album_id, $query = false) {
    $q = $this->createQuery('f')
            ->innerJoin('f.mdAssetAlbum a')
            ->where('f.md_album_id = ?', $md_album_id)
            ->orderBy('f.position ASC');

    if ($query)
      return $q;
    else
      return $q->execute();
  }
}