<?php

/**
 * PluginmdAssetAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdAssetAlbum extends BasemdAssetAlbum
{
  public function hasAvatar()
  {
    return !is_null($this->getMdAssetFileId()) && $this->getMdAssetFileId() != '';
  }
  
  public function getUrl($width, $height, $original = false){
    if($this->hasAvatar()){
      return $this->getMdAsset()->getUrl($width, $height, $original);      
    }else{
      return false;
    }
  }
  
  public static function create($object){
    $base_dir = $object->getBaseDir();
    $object_dir = $object->getObjectDir();
    $relative_path = sfConfig::get('app_sf_media_browser_root_dir') . '/' . $base_dir . '/' . $object_dir;
    
    $mdAssetAlbum = new mdAssetAlbum();
    $mdAssetAlbum->setName('Defecto');
    $mdAssetAlbum->setObjectId($object->getId());
    $mdAssetAlbum->setObjectClass($object->getObjectClass());
    $mdAssetAlbum->setRelativePath($relative_path);
    $mdAssetAlbum->setDescription('Album por defecto');
    $mdAssetAlbum->save();
    
    return $mdAssetAlbum;
  }  
}