<?php

/**
 * PluginmdAssetFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdAssetFile extends BasemdAssetFile {

  private $dimensions;

  public function getRootPath() {
    return sfConfig::get('sf_web_dir ') . substr($this->getMdAssetAlbum()->getRelativePath(), 1);
  }

  public function getPath() {
    return sfConfig::get('sf_web_dir ') . substr($this->getMdAssetAlbum()->getRelativePath(), 1) . '/' . $this->getFilename();
  }

  /**
   *
   * @return string icon file name
   */
  public function getIcon() {
    if ($this->isImage()) {
      return $this->getMdAssetAlbum()->getRelativePath() . '/.thumbnails/' . $this->getFilename();
    }
    return sfMediaBrowserUtils::getIconFromExtension(trim($this->getExtension(), '.'));
  }

  public function getUrl($width, $height, $original = false) {
    if ($original)
      return $this->getMdAssetAlbum()->getRelativePath() . '/' . $this->getFilename();

    $cacheRootDir = $this->getRootPath() . '/.' . $width . 'x' . $height;
    $cacheFile = $cacheRootDir . '/' . $this->getFilename();

    if (!file_exists($cacheFile)) {
      try {
        $img = new sfImage($this->getPath());

        $img->resize($width, $height);

        if (!sfMediaBrowserUtils::checkDirectory($cacheRootDir)) {
          throw new Exception('Filesystem fail');
        }

        $img->saveAs($cacheFile);
      } catch (Exception $e) {
        return $this->getMdAssetAlbum()->getRelativePath() . '/' . $this->getFilename();
      }
    }

    return $this->getMdAssetAlbum()->getRelativePath() . '/.' . $width . 'x' . $height . '/' . $this->getFilename();
  }

  public function getSize() {
    $size = $this->getFilesize();

    $sizes = array('B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');

    $retstring = '%01.2f %s';

    $lastsizestring = end($sizes);

    foreach ($sizes as $sizestring) {
      if ($size < 1024) {
        break;
      }
      if ($sizestring != $lastsizestring) {
        $size /= 1024;
      }
    }
    if ($sizestring == $sizes[0]) {
      $retstring = '%01d %s';
    } // los Bytes normalmente no son fraccionales

    return sprintf($retstring, $size, $sizestring);
  }

  public function isImage() {
    return sfMediaBrowserUtils::getTypeFromExtension(trim($this->getExtension(), '.')) == 'image';
  }

  public function getDimensions() {

    if ($this->isImage()) {
      if (!$this->dimensions) {
        $this->dimensions = getimagesize(sfConfig::get('sf_web_dir ') . substr($this->getMdAssetAlbum()->getRelativePath(), 1) . '/' . $this->getFilename());
      }
      return $this->dimensions;
    }
    return false;
  }

  public function getWidth() {
    if ($this->isImage()) {
      $dimensions = $this->getDimensions();
      return $dimensions[0];
    }
    return 0;
  }

  public function getHeight() {
    if ($this->isImage()) {
      $dimensions = $this->getDimensions();
      return $dimensions[1];
    }
    return 0;
  }

  public function render() {
    
  }

  public function postDelete($event) {
    parent::postDelete($event);

    // try to delete the thumbnail if exists
    try {
      $files = sfFinder::type('file')->name($this->getFilename())->in($this->getRootPath());
      foreach ($files as $file) {
        @unlink($file);
      }
    } catch (sfException $e) {
      
    }
    
  }

}